#!/usr/bin/env python3
"""tools/docs_index.py — regenerate docs/INDEX.md and report orphan docs.

Two duties:
  --check   fail if INDEX.md differs from regeneration or orphans exist
  (default) write INDEX.md and print the orphan report

Navigation model: README.md is the entry root and must link docs/INDEX.md;
INDEX.md (generated) links every doc. So "navigable" = 2 hops from README.
--check fails when INDEX is stale or README fails to link it. The orphan
report (docs linked by NO other doc) stays informational — cross-linking is
quality work, not a gate, because INDEX provides the floor.
"""
from __future__ import annotations
import subprocess

import re
import sys
from pathlib import Path

ECO = Path(__file__).resolve().parents[1]
DOCS = ECO / "docs"
EXEMPT_DIRS = {"history", "desktop"}

LINK_RE = re.compile(r"\]\(([^)#]+?)(?:#[^)]*)?\)")


def md_files() -> list[Path]:
    # Enumerate via git ls-files so the generated INDEX.md is identical in a
    # clean CI checkout and a local tree that has transient, gitignored files
    # (e.g. docs/SESSION_HOP_ALERT.md, written by session_guard on handoff).
    try:
        out = subprocess.run(
            ["git", "ls-files", "--", "docs/"],
            cwd=ECO, capture_output=True, text=True, check=True, timeout=15,
        ).stdout
        paths = [ECO / line for line in out.splitlines()
                 if line.endswith(".md") and not line.endswith("INDEX.md")]
        if paths:
            return sorted(paths)
    except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
        pass  # not a git checkout (or git missing) — fall back to the filesystem scan below
    return sorted(p for p in DOCS.rglob("*.md") if ".git" not in p.parts)


def title_of(path: Path) -> str:
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
        if line.strip():
            return path.stem.replace("_", " ").title()
    return path.stem


def build_index(files: list[Path]) -> str:
    top, by_dir = [], {}
    archived = 0
    for f in files:
        rel = f.relative_to(ECO)
        # history/ is the decision & timeline archive: it is linked once via
        # history/README.md, not enumerated — the INDEX is the map of live docs.
        # history/attic is cold storage (archive-not-delete) inside it.
        if "attic" in rel.parts:
            archived += 1
            continue
        parts = rel.parts[1:-1]
        if parts and parts[0] == "history" and rel.name != "README.md":
            continue
        if not parts:
            top.append(rel)
        else:
            by_dir.setdefault(parts[0], []).append(rel)

    def book_rel(p: Path) -> str:
        # Path relative to docs/INDEX.md; full subpath, never just basename —
        # nested dirs (audits/<dated>/x.md) used to break this link.
        return str(Path(*p.parts[1:]))

    out = ["# Documentation Index",
           "",
           "Generated by tools/docs_index.py — do not hand-edit.",
           "Regenerate: `python tools/docs_index.py`; gate: `--check` in CI.",
           ""]
    if top:
        out.append("## Top level")
        out += [f"- [{title_of(ECO / p)}]({book_rel(p)})" for p in top]
        out.append("")
    for d in sorted(by_dir):
        if d == "history":
            out.append("## History")
            out.append("- [📜 History — timeline & decision archive](history/README.md)")
            out.append("")
            continue
        out.append(f"## {d}/")
        out += [f"- [{title_of(ECO / p)}]({book_rel(p)})" for p in by_dir[d]]
        out.append("")
    if archived:
        out.append(f"_{archived} archived docs under history/attic/ are intentionally "
                   f"not listed (cold storage, see DOCUMENTATION_POLICY)._\n")
    return "\n".join(out)


def find_orphans(files: list[Path]) -> list[Path]:
    linked: set[Path] = set()
    for f in files:
        if f.name == "INDEX.md":
            continue
        text = f.read_text(encoding="utf-8", errors="replace")
        for m in LINK_RE.finditer(text):
            url = m.group(1)
            if "://" in url or url.startswith("mailto:"):
                continue
            target = (f.parent / url).resolve()
            if target.suffix == ".md":
                linked.add(target)
    return [f for f in files
            if f.name != "INDEX.md"
            and f.resolve() not in linked
            and not (set(f.relative_to(DOCS).parts[:-1]) & EXEMPT_DIRS)]


def main() -> int:
    files = md_files()
    new_index = build_index(files)
    index_path = DOCS / "INDEX.md"
    orphans = find_orphans(files)

    if "--check" in sys.argv:
        ok = True
        if not index_path.exists() or index_path.read_text() != new_index:
            print("INDEX.md is stale — run: python tools/docs_index.py")
            ok = False
        readme = (ECO / "README.md").read_text(encoding="utf-8", errors="replace")
        if "docs/INDEX.md" not in readme:
            print("README.md does not link docs/INDEX.md — navigation root broken")
            ok = False
        if orphans:
            print(f"info: {len(orphans)} docs are linked by no other doc "
                  f"(INDEX.md covers them; cross-linking is quality work)")
        return 0 if ok else 1

    index_path.write_text(new_index)
    print(f"INDEX.md regenerated ({len(files)} docs)")
    if orphans:
        print(f"orphans ({len(orphans)}):")
        for o in orphans:
            print(f"  {o.relative_to(ECO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
